"""
train_and_save_model.py
────────────────────────
Trains the Random Forest model (same logic as ecommerce_ai_project.py)
and saves it to models/random_forest_model.pkl for the API to load.

Run:
    python train_and_save_model.py

Output:
    models/random_forest_model.pkl   ← loaded by PredictionService
    models/model_metadata.json       ← version, features, metrics
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score
from datetime import datetime

# ── Config ──────────────────────────────────────────────────────────────────
MODEL_VERSION = "1.0.0"
MODEL_DIR     = "models"
MODEL_PATH    = os.path.join(MODEL_DIR, "random_forest_model.pkl")
META_PATH     = os.path.join(MODEL_DIR, "model_metadata.json")
DATA_PATH     = "ecommerce_data.csv"           # generated by ecommerce_ai_project.py

os.makedirs(MODEL_DIR, exist_ok=True)

# ── Load data ────────────────────────────────────────────────────────────────
print(f"Loading data from {DATA_PATH}...")
if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"{DATA_PATH} not found. Run 'python ecommerce_ai_project.py' first."
    )

df = pd.read_csv(DATA_PATH)
print(f"Loaded {len(df):,} records.")

# ── Feature engineering (must mirror api/services/prediction_service.py) ────
feature_cols = [
    "distance_km",
    "warehouse_load",
    "order_items",
    "past_delays",
    "order_value",
    "promised_delivery_days",
]

warehouse_dummies = pd.get_dummies(df["warehouse"], prefix="warehouse")
X = pd.concat([df[feature_cols], warehouse_dummies], axis=1)
y = df["is_delayed"]

print(f"Features: {list(X.columns)}")
print(f"Class balance — delayed: {y.mean():.2%}, on-time: {1-y.mean():.2%}")

# ── Train / test split ───────────────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

# ── Train Random Forest ───────────────────────────────────────────────────────
print("\nTraining Random Forest...")
model = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    n_jobs=-1,
)
model.fit(X_train, y_train)

# ── Evaluate ─────────────────────────────────────────────────────────────────
y_pred    = model.predict(X_test)
accuracy  = round(accuracy_score(y_test, y_pred), 4)
precision = round(precision_score(y_test, y_pred), 4)
recall    = round(recall_score(y_test, y_pred), 4)

print(f"\nModel Performance:")
print(f"  Accuracy:  {accuracy:.2%}")
print(f"  Precision: {precision:.2%}")
print(f"  Recall:    {recall:.2%}")

# ── Feature importance ────────────────────────────────────────────────────────
importance_df = pd.DataFrame({
    "feature":    X.columns,
    "importance": model.feature_importances_,
}).sort_values("importance", ascending=False)
print("\nTop feature importances:")
print(importance_df.to_string(index=False))

# ── Save model ────────────────────────────────────────────────────────────────
joblib.dump(model, MODEL_PATH)
print(f"\n✅ Model saved to {MODEL_PATH}")

# ── Save metadata ─────────────────────────────────────────────────────────────
metadata = {
    "model_version":     MODEL_VERSION,
    "trained_at":        datetime.utcnow().isoformat(),
    "algorithm":         "RandomForestClassifier",
    "n_estimators":      100,
    "max_depth":         10,
    "features":          list(X.columns),
    "training_samples":  len(X_train),
    "test_samples":      len(X_test),
    "metrics": {
        "accuracy":  accuracy,
        "precision": precision,
        "recall":    recall,
    },
    "feature_importance": importance_df.set_index("feature")["importance"].to_dict(),
}

with open(META_PATH, "w") as f:
    json.dump(metadata, f, indent=2)

print(f"✅ Metadata saved to {META_PATH}")
print("\n🚀 Run 'python app.py' to start the API — model is ready.")
